version: 2
jobs:
  test:
    docker:
      - image: node:10
    working_directory: ~/ci

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Install Puppeteer dependencies
          command: bash .circleci/setup_puppeteer.sh

      - run:
          name: Install tests apps dependencies
          command: |
            npm ci --prefix=src/__tests__/__apps__/basic

      - run:
          name: 'Test: linting'
          command: npm run test:lint

      - run:
          name: 'Test: formatting'
          command: npm run test:formatting

      - run:
          name: 'Test: unit-tests & end-to-end'
          command: npm run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  test:
    jobs:
      - test
